# DATA2x01 Assignment - Data Cleaning Notebook

This notebook cleans the `Region summary_ New South Wales STE 1.csv` dataset.

The cleaning process includes:

1. Loading the CSV file
2. Checking the dataset structure
3. Standardising column names
4. Removing duplicate rows
5. Cleaning text columns
6. Converting year columns to numeric values
7. Handling missing values carefully
8. Saving the cleaned dataset

In [17]:
import pandas as pd
import numpy as np

In [18]:
# Load the raw CSV file
file_path = "data/Region summary_ New South Wales STE 1.csv"

df = pd.read_csv(file_path)

# Display the first few rows
df.head()

,Measure Code,Parent Description,Description,2011,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,ERP_P_20,Estimated resident population - year ended 30 ...,Estimated resident population (no.),NaN,NaN,NaN,NaN,NaN,8046748.0,8110610.0,8097062.0,8166704.0,8341199.0,8479314.0,NaN
1,ERP_21,Estimated resident population - year ended 30 ...,Population density (persons/km2),NaN,NaN,NaN,NaN,NaN,10.0,10.1,10.1,10.2,10.4,10.6,NaN
2,ERP_M_20,Estimated resident population - year ended 30 ...,Estimated resident population - males (no.),NaN,NaN,NaN,NaN,NaN,3999452.0,4030710.0,4025393.0,4059763.0,4149032.0,4217861.0,NaN
3,ERP_F_20,Estimated resident population - year ended 30 ...,Estimated resident population - females (no.),NaN,NaN,NaN,NaN,NaN,4047296.0,4079900.0,4071669.0,4106941.0,4192167.0,4261453.0,NaN
4,ERP_19,Estimated resident population - year ended 30 ...,Median age - males (years),NaN,NaN,NaN,NaN,NaN,36.8,37.2,37.7,37.7,37.5,37.5,NaN

In [19]:
# Check the size of the dataset
print("Number of rows and columns:", df.shape)

# Check column names
print("\nColumn names:")
print(df.columns.tolist())

# Check data types and missing values
print("\nDataset information:")
df.info()

Number of rows and columns: (800, 15)

Column names:
['Measure Code', 'Parent Description', 'Description', '2011', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Measure Code        800 non-null    object
 1   Parent Description  800 non-null    object
 2   Description         800 non-null    object
 3   2011                259 non-null    float64
 4   2015                20 non-null     float64
 5   2016                457 non-null    float64
 6   2017                48 non-null     float64
 7   2018                125 non-null    float64
 8   2019                270 non-null    float64
 9   2020                291 non-null    float64
 10  2021                692 non-null    float64
 11  2022                293 non-null    float64
 12  2023                207 non-null    float64
 13  2024                209 non-null    float64
 14  2025                3 non-null      float64
dtypes: float64(12), object(3)
memory usage: 93.9+ KB

In [20]:
# Display the first 10 rows
df.head(10)

,Measure Code,Parent Description,Description,2011,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,ERP_P_20,Estimated resident population - year ended 30 ...,Estimated resident population (no.),NaN,NaN,NaN,NaN,NaN,8046748.0,8110610.0,8097062.0,8166704.0,8341199.0,8479314.0,NaN
1,ERP_21,Estimated resident population - year ended 30 ...,Population density (persons/km2),NaN,NaN,NaN,NaN,NaN,10.0,10.1,10.1,10.2,10.4,10.6,NaN
2,ERP_M_20,Estimated resident population - year ended 30 ...,Estimated resident population - males (no.),NaN,NaN,NaN,NaN,NaN,3999452.0,4030710.0,4025393.0,4059763.0,4149032.0,4217861.0,NaN
3,ERP_F_20,Estimated resident population - year ended 30 ...,Estimated resident population - females (no.),NaN,NaN,NaN,NaN,NaN,4047296.0,4079900.0,4071669.0,4106941.0,4192167.0,4261453.0,NaN
4,ERP_19,Estimated resident population - year ended 30 ...,Median age - males (years),NaN,NaN,NaN,NaN,NaN,36.8,37.2,37.7,37.7,37.5,37.5,NaN
5,ERP_22,Estimated resident population - year ended 30 ...,Median age - females (years),NaN,NaN,NaN,NaN,NaN,38.6,39.0,39.5,39.6,39.4,39.4,NaN
6,ERP_23,Estimated resident population - year ended 30 ...,Median age - persons (years),NaN,NaN,NaN,NaN,NaN,37.7,38.1,38.6,38.7,38.4,38.4,NaN
7,ERP_18,Estimated resident population - year ended 30 ...,Working age population (aged 15-64 years) (no.),NaN,NaN,NaN,NaN,NaN,5240576.0,5255515.0,5209700.0,5247219.0,5388091.0,5490199.0,NaN
8,ERP_17,Estimated resident population - year ended 30 ...,Working age population (aged 15-64 years) (%),NaN,NaN,NaN,NaN,NaN,65.1,64.8,64.3,64.3,64.6,64.7,NaN
9,ERP_M_2,Estimated resident population - Males - year e...,Males - 0-4 years (no.),NaN,NaN,NaN,NaN,NaN,253365.0,250224.0,246488.0,247060.0,246330.0,243455.0,NaN

In [21]:
# Standardise column names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# Show cleaned column names
df.columns.tolist()

['measure_code',
 'parent_description',
 'description',
 '2011',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024',
 '2025']

In [22]:
# Count rows before removing duplicates
rows_before = df.shape[0]

# Remove duplicate rows
df = df.drop_duplicates()

# Count rows after removing duplicates
rows_after = df.shape[0]

print("Rows before removing duplicates:", rows_before)
print("Rows after removing duplicates:", rows_after)
print("Duplicate rows removed:", rows_before - rows_after)

Rows before removing duplicates: 800
Rows after removing duplicates: 800
Duplicate rows removed: 0

In [23]:
# Text columns that need cleaning
text_cols = ["measure_code", "parent_description", "description"]

# Clean text columns
for col in text_cols:
    if col in df.columns:
        df[col] = df[col].astype(str)
        df[col] = df[col].str.strip()
        df[col] = df[col].str.replace(r"\s+", " ", regex=True)

df[text_cols].head()

,measure_code,parent_description,description
0,ERP_P_20,Estimated resident population - year ended 30 ...,Estimated resident population (no.)
1,ERP_21,Estimated resident population - year ended 30 ...,Population density (persons/km2)
2,ERP_M_20,Estimated resident population - year ended 30 ...,Estimated resident population - males (no.)
3,ERP_F_20,Estimated resident population - year ended 30 ...,Estimated resident population - females (no.)
4,ERP_19,Estimated resident population - year ended 30 ...,Median age - males (years)

In [24]:
# Identify year columns
year_cols = [col for col in df.columns if col.isdigit()]

print("Year columns:")
print(year_cols)

Year columns:
['2011', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

In [25]:
# Convert year columns to numeric values
for col in year_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Check data types after conversion
df[year_cols].dtypes

2011    float64
2015    float64
2016    float64
2017    float64
2018    float64
2019    float64
2020    float64
2021    float64
2022    float64
2023    float64
2024    float64
2025    float64
dtype: object

In [26]:
# Check missing values in each column
missing_values = df.isna().sum()

missing_values

measure_code            0
parent_description      0
description             0
2011                  541
2015                  780
2016                  343
2017                  752
2018                  675
2019                  530
2020                  509
2021                  108
2022                  507
2023                  593
2024                  591
2025                  797
dtype: int64

In [27]:
# Count rows before removing rows with no year data
rows_before = df.shape[0]

# Remove rows where all year columns are missing
df = df.dropna(subset=year_cols, how="all")

# Count rows after cleaning
rows_after = df.shape[0]

print("Rows before removing empty year rows:", rows_before)
print("Rows after removing empty year rows:", rows_after)
print("Rows removed:", rows_before - rows_after)

Rows before removing empty year rows: 800
Rows after removing empty year rows: 800
Rows removed: 0

In [28]:
print("Cleaned dataset shape:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isna().sum())

print("\nDataset information:")
df.info()

Cleaned dataset shape: (800, 15)

Column names:
['measure_code', 'parent_description', 'description', '2011', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

Missing values:
measure_code            0
parent_description      0
description             0
2011                  541
2015                  780
2016                  343
2017                  752
2018                  675
2019                  530
2020                  509
2021                  108
2022                  507
2023                  593
2024                  591
2025                  797
dtype: int64

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   measure_code        800 non-null    object
 1   parent_description  800 non-null    object
 2   description         800 non-null    object
 3   2011                259 non-null    float64
 4   2015                20 non-null     float64
 5   2016                457 non-null    float64
 6   2017                48 non-null     float64
 7   2018                125 non-null    float64
 8   2019                270 non-null    float64
 9   2020                291 non-null    float64
 10  2021                692 non-null    float64
 11  2022                293 non-null    float64
 12  2023                207 non-null    float64
 13  2024                209 non-null    float64
 14  2025                3 non-null      float64
dtypes: float64(12), object(3)
memory usage: 93.9+ KB

In [29]:
df.head(20)

,measure_code,parent_description,description,2011,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,ERP_P_20,Estimated resident population - year ended 30 ...,Estimated resident population (no.),NaN,NaN,NaN,NaN,NaN,8046748.0,8110610.0,8097062.0,8166704.0,8341199.0,8479314.0,NaN
1,ERP_21,Estimated resident population - year ended 30 ...,Population density (persons/km2),NaN,NaN,NaN,NaN,NaN,10.0,10.1,10.1,10.2,10.4,10.6,NaN
2,ERP_M_20,Estimated resident population - year ended 30 ...,Estimated resident population - males (no.),NaN,NaN,NaN,NaN,NaN,3999452.0,4030710.0,4025393.0,4059763.0,4149032.0,4217861.0,NaN
3,ERP_F_20,Estimated resident population - year ended 30 ...,Estimated resident population - females (no.),NaN,NaN,NaN,NaN,NaN,4047296.0,4079900.0,4071669.0,4106941.0,4192167.0,4261453.0,NaN
4,ERP_19,Estimated resident population - year ended 30 ...,Median age - males (years),NaN,NaN,NaN,NaN,NaN,36.8,37.2,37.7,37.7,37.5,37.5,NaN
5,ERP_22,Estimated resident population - year ended 30 ...,Median age - females (years),NaN,NaN,NaN,NaN,NaN,38.6,39.0,39.5,39.6,39.4,39.4,NaN
6,ERP_23,Estimated resident population - year ended 30 ...,Median age - persons (years),NaN,NaN,NaN,NaN,NaN,37.7,38.1,38.6,38.7,38.4,38.4,NaN
7,ERP_18,Estimated resident population - year ended 30 ...,Working age population (aged 15-64 years) (no.),NaN,NaN,NaN,NaN,NaN,5240576.0,5255515.0,5209700.0,5247219.0,5388091.0,5490199.0,NaN
8,ERP_17,Estimated resident population - year ended 30 ...,Working age population (aged 15-64 years) (%),NaN,NaN,NaN,NaN,NaN,65.1,64.8,64.3,64.3,64.6,64.7,NaN
9,ERP_M_2,Estimated resident population - Males - year e...,Males - 0-4 years (no.),NaN,NaN,NaN,NaN,NaN,253365.0,250224.0,246488.0,247060.0,246330.0,243455.0,NaN
10,ERP_M_3,Estimated resident population - Males - year e...,Males - 5-9 years (no.),NaN,NaN,NaN,NaN,NaN,262031.0,261782.0,261143.0,258772.0,256724.0,255976.0,NaN
11,ERP_M_4,Estimated resident population - Males - year e...,Males - 10-14 years (no.),NaN,NaN,NaN,NaN,NaN,252185.0,257935.0,261630.0,263743.0,265954.0,267114.0,NaN
12,ERP_M_5,Estimated resident population - Males - year e...,Males - 15-19 years (no.),NaN,NaN,NaN,NaN,NaN,244004.0,241491.0,238716.0,248468.0,259831.0,265979.0,NaN
13,ERP_M_6,Estimated resident population - Males - year e...,Males - 20-24 years (no.),NaN,NaN,NaN,NaN,NaN,282850.0,276091.0,263020.0,268004.0,287712.0,298284.0,NaN
14,ERP_M_7,Estimated resident population - Males - year e...,Males - 25-29 years (no.),NaN,NaN,NaN,NaN,NaN,303569.0,299182.0,286918.0,286780.0,303510.0,315585.0,NaN
15,ERP_M_8,Estimated resident population - Males - year e...,Males - 30-34 years (no.),NaN,NaN,NaN,NaN,NaN,296769.0,299129.0,295922.0,296203.0,306459.0,312961.0,NaN
16,ERP_M_9,Estimated resident population - Males - year e...,Males - 35-39 years (no.),NaN,NaN,NaN,NaN,NaN,282828.0,289492.0,292156.0,292665.0,296977.0,302006.0,NaN
17,ERP_M_10,Estimated resident population - Males - year e...,Males - 40-44 years (no.),NaN,NaN,NaN,NaN,NaN,250782.0,253126.0,257741.0,264203.0,275142.0,284658.0,NaN
18,ERP_M_11,Estimated resident population - Males - year e...,Males - 45-49 years (no.),NaN,NaN,NaN,NaN,NaN,260244.0,261043.0,256646.0,250766.0,248418.0,248748.0,NaN
19,ERP_M_12,Estimated resident population - Males - year e...,Males - 50-54 years (no.),NaN,NaN,NaN,NaN,NaN,235380.0,238082.0,244279.0,249894.0,254407.0,256312.0,NaN

In [30]:
# Count records by parent description
df["parent_description"].value_counts()

parent_description
Estimated resident population - Males - year ended 30 June                 36
Estimated resident population - Females - year ended 30 June               36
Estimated resident population - Persons - year ended 30 June               36
Personal income in Australia - year ended 30 June                          29
Commuting to work - Persons aged 15 years and older - Census               24
                                                                           ..
Self-assessed health                                                        1
Private health insurance - year ended 30 June                               1
Higher Education Loan Program (HELP) - year ended 30 June                   1
Average number of children per family - Families with children - Census     1
Land area                                                                   1
Name: count, Length: 104, dtype: int64

In [31]:
# Save cleaned dataset
output_path = "data/cleaned_region_summary_nsw.csv"

df.to_csv(output_path, index=False)

print("Cleaned file saved as:", output_path)

Cleaned file saved as: data/cleaned_region_summary_nsw.csv

In [32]:
# Reload the cleaned file to check it
cleaned_df = pd.read_csv("data/cleaned_region_summary_nsw.csv")

cleaned_df.head()

,measure_code,parent_description,description,2011,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,ERP_P_20,Estimated resident population - year ended 30 ...,Estimated resident population (no.),NaN,NaN,NaN,NaN,NaN,8046748.0,8110610.0,8097062.0,8166704.0,8341199.0,8479314.0,NaN
1,ERP_21,Estimated resident population - year ended 30 ...,Population density (persons/km2),NaN,NaN,NaN,NaN,NaN,10.0,10.1,10.1,10.2,10.4,10.6,NaN
2,ERP_M_20,Estimated resident population - year ended 30 ...,Estimated resident population - males (no.),NaN,NaN,NaN,NaN,NaN,3999452.0,4030710.0,4025393.0,4059763.0,4149032.0,4217861.0,NaN
3,ERP_F_20,Estimated resident population - year ended 30 ...,Estimated resident population - females (no.),NaN,NaN,NaN,NaN,NaN,4047296.0,4079900.0,4071669.0,4106941.0,4192167.0,4261453.0,NaN
4,ERP_19,Estimated resident population - year ended 30 ...,Median age - males (years),NaN,NaN,NaN,NaN,NaN,36.8,37.2,37.7,37.7,37.5,37.5,NaN

The dataset has been cleaned successfully. Column names were standardised, duplicate rows were removed, text fields were trimmed, and year columns were converted into numeric values. Missing values were kept when only some years were unavailable, because different indicators may be reported in different years. Rows were only removed when all year values were missing.